name: "Test the merged-pr-info-action in a pull request"
on:
  pull_request:

jobs:
  comment:
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Pass the relative path to use the action
      - uses: ./
        id: merged-pr-info
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Comment to the pull request it self"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          script: |
            const pr_number = "${{ steps.merged-pr-info.outputs.pull_request_number }}";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: "@" + "${{ steps.merged-pr-info.outputs.pull_request_creator }}" +  " The Action worked!"
            });
            console.log(`Commented to the pull request ${pr_number}`);
